package io.github.Andrew6rant.foodexpansion;

public class ItemNames {
    public static final String BACON = "bacon";
    public static final String BACON_AND_EGG = "bacon_and_egg";
    public static final String BAT_SOUP = "bat_soup";
    public static final String BAT_WING = "bat_wing";
    public static final String BEETROOT_NOODLES = "beetroot_noodles";
    public static final String BLAZE_CREAM = "blaze_cream";
    public static final String CACTUS_FRUIT = "cactus_fruit";
    public static final String CARROT_PIE = "carrot_pie";
    public static final String CARROT_SEED_SOUP = "carrot_seed_soup";
    public static final String CHOCOLATE_BAR = "chocolate_bar";
    public static final String COMPRESSED_FLESH = "compressed_flesh";
    public static final String COOKED_BACON = "cooked_bacon";
    public static final String COOKED_BAT_WING = "cooked_bat_wing";
    public static final String COOKED_HORSE_MEAT = "cooked_horse_meat";
    public static final String COOKED_LLAMA_MEAT = "cooked_llama_meat";
    public static final String COOKED_MUSHROOM = "cooked_mushroom";
    public static final String COOKED_OCELOT_MEAT = "cooked_ocelot_meat";
    public static final String COOKED_PARROT_MEAT = "cooked_parrot_meat";
    public static final String COOKED_POLAR_BEAR_MEAT = "cooked_polar_bear_meat";
    public static final String COOKED_SQUID = "cooked_squid";
    public static final String COOKED_WOLF_MEAT = "cooked_wolf_meat";
    public static final String DOUGH = "dough";
    public static final String FORBIDDEN_FRUIT = "forbidden_fruit";
    public static final String FRIED_EGG = "fried_egg";
    public static final String GOLDEN_FEAST = "golden_feast";
    public static final String HORSE_MEAT = "horse_meat";
    public static final String JELLY = "jelly";
    public static final String LLAMA_MEAT = "llama_meat";
    public static final String LOLLIPOP = "lollipop";
    public static final String MELON_SALAD = "melon_salad";
    public static final String NETHER_WART_SOUP = "nether_wart_soup";
    public static final String OCELOT_MEAT = "ocelot_meat";
    public static final String PARROT_MEAT = "parrot_meat";
    public static final String POLAR_BEAR_MEAT = "polar_bear_meat";
    public static final String ROASTED_SEED = "roasted_seed";
    public static final String SPIDER_SOUP = "spider_soup";
    public static final String SQUID = "squid";
    public static final String STARVING_FRUIT = "starving_fruit";
    public static final String VEGGIE_STEW = "veggie_stew";
    public static final String WOLF_MEAT = "wolf_meat";
}
