modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="foodexpansion"
version="${file.jarVersion}"
displayName="Food Expansion: Reimagined"
authors="raulsmartin & Lellson"
description="Adds various food into the game"
[[dependencies.foodexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.foodexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
